name:  CD

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    strategy:
    
      matrix:
        channel: [Dev, Prod]
        targetRuntime: [win-x86, win-x64]
        include:

          - channel: Dev
            ChannelName: Dev
            Configuration: Debug
            
          - channel: Prod          
            ChannelName: Prod
            Configuration: Release

    runs-on: windows-latest
      
    steps:
    - name: Set Environment Variables
      shell: bash
      run: echo "release_name="OStimAnimationTool-${GITHUB_REF#refs/*/}-${{ matrix.targetRuntime }} (${{ matrix.ChannelName }})"" >> $GITHUB_ENV
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish OStimAnimationTool.sln -c ${{ matrix.Configuration }} -r ${{ matrix.targetRuntime }} -o $env:release_name --no-restore
      
    - name: Package Archive
      run: |
        7z a -tzip "$env:release_name.zip" "./$env:release_name/*"
        rm -r "$env:release_name"
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "OStimAnimationTool-*"
